<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/09/16 22:19:10

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=agencia',
  'username' => 'root',
  'password' => 123456,
  'name' => 'doctrine',
)),);
