default:
  http_metas:
    content-type: text/html

  metas:
    title:        Agencia de Festejos Inversiones SAJ c.a
    description:  Agencia de Festejos Inversiones 
    keywords:     agencia festejos inversiones 
    language:     en
    robots:       index, follow

  stylesheets:    [main.css, style.css]

  javascripts:    []

  has_layout:     on
  layout:         layout
